export const DEFAULT_CATEGORIES = [
  { name: "Food", iconName: "Coffee", color: "#34D399" },
  { name: "Groceries", iconName: "ShoppingCart", color: "#F59E0B" },
  { name: "Rent", iconName: "Home", color: "#10B981" },
  { name: "Shopping", iconName: "ShoppingBag", color: "#EC4899" },
  { name: "Travel", iconName: "Plane", color: "#60A5FA" },
  { name: "Transport", iconName: "Car", color: "#3B82F6" },
  { name: "Entertainment", iconName: "Play", color: "#8B5CF6" },
  { name: "Subscriptions", iconName: "CreditCard", color: "#F472B6" },
  { name: "Health", iconName: "Activity", color: "#EF4444" },
  { name: "Work", iconName: "Briefcase", color: "#6366F1" },
  { name: "Education", iconName: "Book", color: "#0EA5E9" },
  { name: "Music", iconName: "Music", color: "#A855F7" },
  { name: "Gifts", iconName: "Gift", color: "#F43F5E" },
  { name: "Dining", iconName: "Utensils", color: "#FB923C" },
  { name: "Mobile", iconName: "Smartphone", color: "#64748B" },
  { name: "Photography", iconName: "Camera", color: "#14B8A6" },
  { name: "Design", iconName: "Palette", color: "#EC4899" },
  { name: "Fitness", iconName: "Dumbbell", color: "#22C55E" },
  { name: "Ideas", iconName: "Zap", color: "#EAB308" },
  { name: "Favorites", iconName: "Star", color: "#FACC15" },
  { name: "Love", iconName: "Heart", color: "#F87171" },
  { name: "Other", iconName: "PenTool", color: "#9CA3AF" },
];
